### ISSUE TITLE
Discord Module roadmap

### ISSUE THREAD

**Issue by btwonion** [RediCloud/core-modules#1]
**public**
- [x] rule system
- [ ] forum suggestion extension
- [ ] poll system
- [ ] bug fixed notification (dm)
- [ ] verify system
- [ ] discussions
- [x] ticket system (incl. pre check concern)

**team**
- [ ] cloud manage command
- [x] moderation
